server:
  port: 39081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://localhost:3306/hypad?serverTimezone=GMT%2B8&useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl